apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-configmap
data:
  API_GATEWAY_PORT: "5000"
  AUTH_SERVICE_URL: "http://user-service:5000"
  USER_SERVICE_URL: "http://user-service:5000"
  RESTAURANT_SERVICE_URL: "http://localhost:4000"

