apiVersion: v1
kind: ConfigMap
metadata:
  name: kitchen-service-configmap
data:
  URL: "0.0.0.0:5000"
  KITCHEN_SERVICE_PORT: "5000"
  MYSQL_ROOT_PASSWORD: "randomp"
  MYSQL_DATABASE: humf_kitchen_db
  MYSQL_HOST: "localhost"
  MYSQL_PORT: "3306"
  MYSQL_USERNAME: root
  MYSQL_PASSWORD: randomp
  MYSQL_SYNCHRONIZE: "true"
  RABBIT_MQ_URI: amqp://rabbitmq-service:5672
  RABBIT_MQ_NOTIFICATION_QUEUE: notification
  ORDER_SERVICE_URL: http://order-service:5000


