apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels: 
    app: order-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: mongodb-order-service
          image: mongo:7.0.2-jammy
          ports:
            - containerPort: 27017
              name: https
              protocol: TCP
          envFrom:
            - configMapRef:
                name: order-service-configmap
        - name: order-service
          image: ragdoll888/humf-order-service:v3.0.0
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP
          envFrom:
            - configMapRef:
                name: order-service-configmap
            - secretRef:
                name: order-service-secret
