# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-user-service-deployment
#   labels: 
#     app: mysql-user-service

# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql-user-service
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxSurge: 3
#   template:
#     metadata:
#       labels:
#         app: mysql-user-service
#     spec:
#       containers:
#         - name: mysql-user-service
#           image: mysql:8.1
#           ports:
#             - containerPort: 3306
#           envFrom:
#             - configMapRef:
#                 name: user-service-configmap
#             - secretRef:
#                 name: user-service-secret
#           volumeMounts:
#             - name: mysql-persistent-storage
#               mountPath: /var/lib/mysql

#       volumes:
#         - name: mysql-persistent-storage
#           persistentVolumeClaim:
#             claimName: mysql-pvc 

# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mysql-pvc
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 10Gi 

