apiVersion: v1
kind: ConfigMap
metadata:
  name: order-service-configmap
data:
  ORDER_SERVICE_HOST: "0.0.0.0"
  PORT: "5000"
  MONGODB_URL: "mongodb://127.0.0.1:27100/order-service"
  ORDER_SERVICE_PORT: "5000"
  ORDER_SERVICE_MONGODB_SERVER: "mongodb-order-service"
  ORDER_SERVICE_MONGODB_PORT: "27017"
  ORDER_SERVICE_MONGODB_DATABASE: "order-service"

