apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deployment
  labels: 
    app: notification-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: mongodb-notification-service
          image: mongo:7.0.2-jammy
          ports:
            - containerPort: 27017
              name: https
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notification-service-configmap
        - name: notification-service
          image: bbbbz/humf-notification-service:1.0.0
          ports:
            - containerPort: 5000
              name: grpc
              protocol: TCP
          envFrom:
            - configMapRef:
                name: notification-service-configmap
