apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-kitchen-service-deployment
  labels: 
    app: mysql-kitchen-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-kitchen-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: mysql-kitchen-service
    spec:
      containers:
        - name: mysql-kitchen-service
          image: mysql:8.1
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: kitchen-service-configmap
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql

      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: kitchen-mysql-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kitchen-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 

