apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-service-deployment
  labels: 
    app: rabbitmq-service

spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 3
  template:
    metadata:
      labels:
        app: rabbitmq-service
    spec:
      containers:
        - name: rabbitmq-service
          image: rabbitmq:3.8.3-management
          ports:
            - containerPort: 5672
